DROP DATABASE IF EXISTS setup;
CREATE DATABASE setup;
USE setup;
/**
DROP TABLE IF EXISTS Staff CASCADE;
DROP TABLE IF EXISTS Authors CASCADE;
DROP TABLE IF EXISTS Editors CASCADE;
DROP TABLE IF EXISTS Publications CASCADE;
DROP TABLE IF EXISTS Books CASCADE;
DROP TABLE IF EXISTS Chapters CASCADE;
DROP TABLE IF EXISTS PeriodicPublication CASCADE;
DROP TABLE IF EXISTS Issue CASCADE;
DROP TABLE IF EXISTS Articles CASCADE;
DROP TABLE IF EXISTS Topics CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Distributors CASCADE;
**/

-- Create tables --

CREATE TABLE Staff (
sid INT NOT NULL AUTO_INCREMENT,
sname VARCHAR(50) NOT NULL,
stype VARCHAR(30) NOT NULL,
sdate DATE NOT NULL,
periodicity INT NOT NULL,
dob DATE NOT NULL,
gender VARCHAR(20) NOT NULL,
phone VARCHAR(20) NOT NULL,
pay FLOAT NOT NULL,
PRIMARY KEY (sid, sdate)
);


CREATE TABLE Publications (
pid INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(250) NOT NULL,
ptype VARCHAR(30) NOT NULL,
dop DATE NOT NULL,
url VARCHAR(2048) NOT NULL,
price FLOAT NOT NULL
);

CREATE TABLE Books(
pid INT AUTO_INCREMENT PRIMARY KEY,
ISBN VARCHAR(50) NOT NULL,
edition INT,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Chapters(
chno INT AUTO_INCREMENT PRIMARY KEY,
chtitle VARCHAR(150) NOT NULL,
url VARCHAR(2048) NOT NULL,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE PeriodicPublication (
pid INT PRIMARY KEY,
periodicity INT NOT NULL,
pptype VARCHAR(10) NOT NULL,
doi DATE NOT NULL,
FOREIGN KEY(pid) REFERENCES Publications(pid)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Issue(
ino INT PRIMARY KEY,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Articles(
aid INT AUTO_INCREMENT PRIMARY KEY,
atitle VARCHAR(350) NOT NULL,
doc DATE NOT NULL,
url VARCHAR(2048) NOT NULL
);

CREATE TABLE Topics(
tname VARCHAR(50) PRIMARY KEY
);

CREATE TABLE Orders(
oid INT AUTO_INCREMENT PRIMARY KEY,
price FLOAT NOT NULL,
copies INT NOT NULL,
shcost FLOAT NOT NULL,
odate DATE NOT NULL
);

CREATE TABLE Distributors(
did INT AUTO_INCREMENT PRIMARY KEY,
dname VARCHAR(50) NOT NULL,
dtype VARCHAR(20) NOT NULL,
city VARCHAR(50) NOT NULL,
address VARCHAR(150) NOT NULL,
contact VARCHAR(50) NOT NULL,
phno VARCHAR(20) NOT NULL,
tot_balance FLOAT NOT NULL
);

CREATE TABLE ConsistOf(
oid INT,
pid INT,
FOREIGN KEY(oid) REFERENCES Orders(oid) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Make(
did INT,
oid INT,
FOREIGN KEY(did) REFERENCES Distributors(did) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(oid) REFERENCES Orders(oid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Contain(
pid INT,
aid INT,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(aid) REFERENCES Articles(aid) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE Edit(
pid INT,
sid INT,
sdate DATE,
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(sid, sdate) REFERENCES Staff(sid, sdate)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE HasTopics(
pid INT,
tname VARCHAR(50),
FOREIGN KEY(pid) REFERENCES Publications(pid) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(tname) REFERENCES Topics(tname) ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE WriteArticle(
aid INT,
sid INT,
sdate DATE,
FOREIGN KEY(aid) REFERENCES Articles(aid) ON UPDATE CASCADE
ON DELETE SET NULL,
FOREIGN KEY(sid, sdate) REFERENCES Staff(sid, sdate)
ON UPDATE CASCADE
ON DELETE SET NULL
);

CREATE TABLE WriteBook(
pid INT,
sid INT,
FOREIGN KEY(sid, sdate) REFERENCES Staff(sid, sdate)
ON UPDATE CASCADE
ON DELETE SET NULL
);